function Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE)
P0=A^2/(2*R0);
ran=RE*A^2/(4*E*R0);
Amax=R0*E/(R0+RE);
pr=ran*100;

Fig=figure('Name','Calcule',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.6 0.4],...
    'NumberTitle','off','Color',[0.75 0.75 0.75 0.75]);
if(R0<=0||RE<=0 || E<=0 || A<=0)
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.12 0.14 0.4 0.07],...
    'FontSize',17,...
    'BackgroundColor','r',...
    'string','(INTRODUCETI VALORI POZITIVE');
P0=0;Amax=0;ran=0;pr=0;Ptot=0;

end
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.24 0.58 0.06 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String','P0=');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.3 0.58 0.06 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String',P0,...
    'Callback','P0=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.24 0.48 0.15 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String','[W] Ptotal=');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.39 0.48 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String',Ptot,...
    'Callback','Ptot=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.24 0.67 0.07 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String','ran=');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.3 0.67 0.06 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String',ran,...
    'Callback','ran=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.24 0.76 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String','Amax=');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.76 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String',Amax,...
    'Callback','Amax=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);')
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.36 0.67 0.06 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String','=>');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.41 0.67 0.06 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String',pr,...
    'Callback','pr=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.47 0.67 0.06 0.1],...
    'FontSize',15,...
    'BackgroundColor','w',...
    'String','%');

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0. 0.23 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[V] E=');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.09 0.23 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',E,...
    'Callback','E=str2num(get(gco, ''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');


uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.56, 0.1 0.1], ... 
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[ohm] RE =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.1 0.58 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',RE,...
    'Callback','RE=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);'); 


uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.66 0.1 0.1], ...  
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[ohm] R0 =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.1 0.69 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',R0,...
    'Callback','R0=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.36 0.1 0.1], ...
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[V] A =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.09 0.39 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',A,...
    'Callback','A=str2num(get(gco,''string'')),close;Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
i=imread('poza3.png');
imshow(i);
set(gca,'units','normalized','position',[0.42 0.1 0.72 0.63]);

end