function Graficee(E,R0,RE,A,A0,f,type,ph,N)
Fig=figure('name','Grafice',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.6 0.4],...
    'Color',[0.75 0.75 0.75 0.75],'NumberTitle','off');

uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0 0.95 0.3 0.05],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','Curentul prin circuit |Tensiunea de intrare| Tensiunea de iesire | Ambele tensiuni | I0 in functie de V0 | Vi in functie de V0',...
    'Value',type,...
    'Callback','type=get(gco,''value''),close,Graficee(E,R0,RE,A,A0,f,type,ph,N)');

T=1./f;
t=0:T/100:N*T;
Vi=A0+A*sin(2*pi*f*t+ph);
V0=Vi-0.7;
I0=V0./R0;
Ire=(V0+Vi)./RE;
Ic=I0+Ire;
if(Ic==0)
    V0=-R0.*E./(R0+RE);
end
if( R0==0)
    uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.32 0.16],...
    'FontSize',17,...
    'BackgroundColor','r',...
    'string','Curentul I0 si Ic nu exista');
    I0=0;
end
if(E==0)
     uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.32 0.16],...
    'FontSize',17,...
    'BackgroundColor','r',...
    'string','Tensiunea V0 nu exista');
     V0=0;
end
if(R0<0||RE<0||f<0||f==0)
     uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.32 0.16],...
    'FontSize',17,...
    'BackgroundColor','r',...
    'string','Nu se pot efectua calculele (valoare negativa)');
    I0=0;Ic=0;Ire=0;Vi=0;V0=0;
end
if(RE==0) 
    uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.32 0.16],...
    'FontSize',17,...
    'BackgroundColor','r',...
    'string','Curentul Ic si Ire nu exista');
end
if(type==1)
    subplot(122);
    plot(t,Ire,'-b');         
    hold on;         
    plot(t,I0,'--g');
    hold on;
    plot(t,Ic,'--r');
    hold on;
    grid on; 
    title('Reprezentare curenti');
    xlabel('timp [s]');       
    ylabel('Curent [A]');  
    legend('Ire','I0','Ic');
elseif(type==2)
     subplot(122);
    plot(t,Vi,'-r');         
    hold on;         
    grid on; 
    title('Reprezentare tensiune de intrare | Vi = A0 + A * sin (2 * pi * f * t + ph)');
    xlabel('timp [s]');       
    ylabel('Amplitudine [V]');  
    legend('Vi'); 
elseif(type==3)
    subplot(122);
    plot(t,V0,'--b');
    hold on;
    grid on;
    title('Reprezentare tensiunea de iesire');
    xlabel('timp[s]');
    ylabel('amplitudinea [A]');
    legend('V0');
elseif(type==4)
    subplot(122);
    plot(t,Vi,'r');
    hold on;
    plot(t,V0,'g');
    hold on;
    grid on;
    title('Vi si V0');
    xlabel('timp[s]');
    ylabel('amplitudinea [A]');
    legend('Vi','V0');
elseif(type==5)
    subplot(122);
    plot(t,I0,'r',t,V0,'b');
    hold on;
    grid on;
    title('Io in functie de V0');
    xlabel('timp[s]');
    ylabel('amplitudinea [A]');
    legend('I0','V0');
elseif(type==6)
    subplot(122);
    plot(Vi,V0);
    hold on;
    grid on;
    title('Vi in functie de V0');
    xlabel('Vi [V]');
    ylabel('V0 [V]');

end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0. 0.07 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[V] E=',...
    'Callback','');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.09 0.09 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',E,...
    'Callback','E=str2num(get(gco, ''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);');

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0. 0.17 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','N=',...
    'Callback','');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.09 0.2 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',N,...
    'Callback','N=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);');

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0. 0.27 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','ph=',...
    'Callback','');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.09 0.29 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',ph,...
    'Callback','ph=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);');

uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.36 0.1 0.1], ...
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[V] A =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.09 0.39 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',A,...
    'Callback','A=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);');


uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.46, 0.1 0.1], ... 
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[V] A0 =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.09 0.48 0.1 0.1],...
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',A0,...
    'Callback','A0=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);'); 
uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.56, 0.1 0.1], ... 
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[ohm] RE =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.1 0.58 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',RE,...
    'Callback','RE=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);'); 
uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0. 0.66 0.1 0.1], ...  
    'FontSize',14,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','[ohm] R0 =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.1 0.69 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String',R0,...
    'Callback','R0=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);');
uicontrol('Style','text', ...
    'Units','normalized', ... 
    'Position',[0 0.77 0.1 0.1], ...  
     'BackgroundColor',[0.75 0.75 0.75 0.75],...
     'FontSize',15,...
    'String','[Hz] f =  ');
uicontrol('Style','edit',...   
    'Units','normalized',...  
    'Position',[0.08 0.79 0.1 0.1],...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'FontSize',12,...
    'String',f,...
    'Callback','f=str2num(get(gco,''string'')),close;Graficee(E,R0,RE,A,A0,f,type,ph,N);');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.34 0.4 0.1 0.1],...
    'FontSize',15,...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'String','Legenda',...
    'Callback','poza2();');

end
