type=1;
E=10;
A=2;
A0=0;
R0=10;
RE=10;
f=50; 
N =2;
ph=0;
P0=A^2/(2*R0);
ran=RE*A^2/(4*E*R0);
Amax=R0*E/(R0+RE);
pr=ran*100;

Ptot=E^2/RE-(1/R0+1/RE)*A^2/2+R0*E^2/(2*(R0+RE)^2)+A^2/(2*RE)+E^2/RE;
fig=figure('Name','Proiect',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.6 0.4],...
    'NumberTitle','off','Color',[0.75 0.75 0.75 0.75]);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.9 0.5 0.1],...
    'String','Amplificator de putere in clasa A', ...
    'fontsize',24,...
    'FontAngle','italic',...
    'BackgroundColor',[0.75 0.75 0.75 0.75],...
    'Callback',' ');
m=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.1 0.4 0.2 0.1],...
    'FontSize',18,...
    'String','Schema',...
    'Callback','buton();'); 
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.1 0.5 0.2 0.1],...
    'FontSize',18,...
    'String','Documentatie',...
    'Callback','open Documentatie.pdf');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.1 0.6 0.2 0.1],...
    'FontSize',18,...
    'String','Grafice',...
    'Callback','Graficee(E,R0,RE,A,A0,f,type,ph,N);');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.1 0.7 0.2 0.1],...
    'FontSize',18,...
    'String','Calcule',...
    'Callback','Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.1 0.3 0.2 0.1],...
    'FontSize',15,...
    'String','Prezentare Proiect',...
    'Callback','open Prezentare.pptx');
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.1 0.7 0.2 0.1],...
    'FontSize',18,...
    'String','Calcule',...
    'Callback','Calcule(P0,ran,Amax,pr,Ptot,A,E,R0,RE);');
i=imread('amp.png');
imshow(i);
set(gca,'units','normalized','position',[0.15 0.05 0.95 0.8]);
